apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: external-dns
    helm:
      values: |
        provider: linode
        linode:
          secretName: "linode-token"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true