apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
    repoURL: https://charts.jetstack.io
    targetRevision: 1.6.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true