apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: metrics-server
    helm:
      values: |
        apiService:
          create: true
        extraArgs:
          kubelet-insecure-tls: true
          kubelet-preferred-address-types: InternalIP
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.10.14
  syncPolicy:
    automated:
      prune: true
      selfHeal: true