apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - secretName: argocd.tlnguyen.com
      hosts:
        - argocd.tlnguyen.com
  rules:
    - host: argocd.tlnguyen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
