apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: argocd.tlnguyen.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
