apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBfS/+/AOBI8YXFG86NjfgS3rJueS9MuG3YLbIvMyEO9N0huK+Ov+PD0ijzNkoSoWm0GwH7Wu7xZoxs1xDNXS1mmUKN/chh78ll+cPGq/JKTI/RytB/dDzwSr0Xi/Q595jubAnuF7R84/5RevCgG/RJpkqpAzj5B6c7SY+o4MHHO9obQqzmMLEnnPkcvkbdhXi1gT10HyCljt1iFhih5JPtq2Kujc9Jl144kdj5yNf3PPW6VnTMTV3clmJfIf9BNRp8RODX1trc3r0GD1JXQG6ynH/M5fB9vImNLnEzKKCCzfnemqBowC6UgDxcrhISLcBw+pdq8I2B+kdjBnQboj+RBKDK1+KeMCA3shGEHQk2Xc9jxvzV65zwQV51YGvCBVw9q+YixY5+Z5HPR4zUQwgu3iyhCI+Iug3Dq3pdC6vwTCQ7fMm5kSJ1LxsuMBwcV6XcVxIDtged9EKRjx4ys+WLvmEN+mpuAJVH45hdIfwGhB/Xrt4m0ZfBvq19CYhzuugUvklwDoc3Wia3zC0SdozmZwLNMFn9ITieHIghsY9i1e7zBjjeToQol6gHBOAGf7OJlZSl0VD/XZpy6wR+tzVStC6Aa9LTpcHU/9Xj/iaf+Xd8/8GQv6ZMoHdZgyx0rhI6SL9jqR4OwN+9egH70JDYhS71adw6G7qT9HofKM9QOJrkjG2QBkMJCkhGqEp8pVdA2EynNDIQ/zX4E/YsuQDUB8H/ajO6EqBCwKp+2A625L1bcYFy2Qfb
    username: AgB3iOveLGP6i2mggOynYwI4/22RcBo78LrSHb75VfpQcaWUDGc/Qky5shQvVQrw2//Ra+Ia9UbDXoxwhTimQOaaK0uo0OGFAcrClLXUzbwtUlPcagLg2csHRO+do2dbRThssC1r8DZFvokBgBLUj7IXMH/KD/ELjpxzunNHgHhQQyQuboaYOhINm708fNV1sGN+QWO9MmYRsDk6FG+SzgteLuS0J8Zj4zLjtzZMcZndL/dRjQe2ErRq2VwpD5seq5Q+GUqrQLo17qalGxanYXcd52+S/quPRpyDDzhjXZAMgNWGoul+zD2IM8sy6IV59R/WssN7zYH+oU9Cbz+l943Ph3blF8BQxVePMcqkP+mdHQ+FK9NnaDTylxnmNAOT0/3ZDyGxlffNLO/lMbtTGAVo2m74EQY3gZNO+SPqMgGLO9ts1YyAPNDvVT4ahvvneHtWUIPbpxzklgIIhUnHCZkT1ZunbcrZkuHYxuKAHk61dfaUml14doKOltOInK9SxbQAYBr6skC3Ls4Sg+fnirfzm5BTWgg6nYsfWdMzbycircDy4XQTmJdRwQ9l8y0cRTkGiVHKMMgAsk+JNPTo3t3M/1QNkwvZPWJqhWfhc7WhgXv6WbqCSCJ9sLtxnSqX+C6MLifgui7E1BwecE7D/gb/bG6g87bLHungragETIr3R4qURVo7U+WCOrG1Xa3BUpltWVfy0JYOM8OydQGdMwgQme9C1uO7zAE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-creds
      namespace: argocd

