apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: toolkit
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/tl-nguyen/tlnguyen-com-infra.git
    targetRevision: HEAD
  destination:
    namespace: toolkit
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true